version: '2.1'
orbs:
  win: circleci/windows@5.0
jobs:
  build:
    executor: win/server-2022
    steps:
      - run:
          name: Set Email
          command: echo "EMAIL_SECRET=sachithdilshan431@gmail.com" > secrets.txt
      - run:
          name: Download setup
          command: |
            Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/SachithDilshan404/tcloud/main/down.bat' -OutFile 'down.bat'
      - run:
          name: run setup
          command: cmd /c down.bat
      - run:
          name: Download loop
          command: |
            Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/SachithDilshan404/Photos-rep/main/loop.ps1' -OutFile 'loop.ps1'
      - run:
          name: Enable looper
          command: powershell -File 'loop.ps1'
            
      
workflows:
  my-workflow:
    jobs:
      - build
