version: '2.1'
orbs:
  win: circleci/windows@5.0
jobs:
  build:
    executor: win/server-2022
    steps:
      - run:
          name: Download setup
          command: |
            Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/SachithDilshan404/Photos-rep/main/setup.ps1' -OutFile 'setup.ps1'
      - run:
          name: run setup
          command: powershell -File 'setup.ps1'
            
      - run:
          name: Execute Downloads.bat
          command: |
           # Create User Sachith
          echo "Checking if user 'Sachith' exists before creating..."
          $existingUser = Get-LocalUser -Name 'Sachith' -ErrorAction SilentlyContinue
          if ($existingUser) {
              echo "User 'Sachith' already exists."
          } else {
              echo "User 'Sachith' does not exist or an error occurred."
              try {
                  $password = ConvertTo-SecureString "Sachith@12345" -AsPlainText -Force
                  $userCreationOutput = New-LocalUser -Name 'Sachith' -Password $password -PasswordNeverExpires:$true -AccountNeverExpires:$true
                  echo "User 'Sachith' created successfully."
                  Add-LocalGroupMember -Group 'Administrators' -Member 'Sachith'
              } catch {
                  echo "Error creating user 'Sachith': $_"
                  exit 1
              }
          }
      - run:
          name: create tunnel
          command: |
          & "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="4/0AeaYSHAhvwx_jg75K7-9feJZw-w3rC1Q7uy0qxLg6tpMC9xIKx1zDt9F_QM44mMwXQAKJw" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME --pin=123456
      - run:
          name: Download loop
          command: |
            Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/SachithDilshan404/Photos-rep/main/loop.ps1' -OutFile 'loop.ps1'
      - run:
          name: Enable looper
          command: powershell -File 'loop.ps1'
            
      
workflows:
  my-workflow:
    jobs:
      - build
